### ISSUE TITLE
Close icon on modal is not visible

### ISSUE THREAD

**Issue by AndrewCraswell** [kiva/ui#1302]
Sometime recently the close icon on the modal that displays after you've successfully made a loan is no longer visible.

```
Browser: Chrome 78.0.3904.97 (Official Build) (64-bit)
OS: Windows 10
Current Git Hash: 4183dd3ecc80d9ca802f253af564d7c2e960f684
Branch: release-11152019
```

<img width="674" alt="MissingIcon" src="https://user-images.githubusercontent.com/1908292/69017547-a9e1a500-095c-11ea-94d8-7a0611f0ea9f.png">

**Comment by go-bears** [comment]
Thanks for being a part of the Kiva community @AndrewCraswell !  
We filter web bugs through Community Support and its contact page: https://www.kiva.org/help?contactus=1

appreciate the eagle eyes!

**Comment by emuvente** [comment]
Thanks for sharing the issue @AndrewCraswell. It was closed because it was fixed and also happens to not apply to this project.

**Comment by AndrewCraswell** [comment]
Is the project it applies to another open source repo?

**Comment by go-bears** [comment]
If you're interested in contributing to Kiva's open source project, you might be interested in the Kiva's crowdvet project.  😄 
https://github.com/kiva/crowdvet.org/tree/develop
