### ISSUE TITLE
Need any volunteers?

### ISSUE THREAD

**Issue by jhannah** [kiva/ui#4904]
I’ve been coding for 25 years, the last 10 of which were focused primarily on REST API development. My contract ended last Friday, so I’m happy to volunteer to do open source work for you.

Do you have any open source issues I can work? I don’t see any?

 https://github.com/kiva/ui
 https://github.com/kiva/api

Do you have a programmer chat room anywhere I could join?

Thanks,

Jay Hannah
1-402-598-7782
https://www.kiva.org/lender/jhannah

**Comment by mcstover** [comment]
@jhannah Thanks for reaching out! I've sent along this message to some folks in the org that may be able to help connect you with appropriate volunteer projects for Kiva!
